name: Build and deploy BookValut API

on:
  push:
    branches: [main]

# Workflow of the pipeline
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: github
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x
      
      - name: Configure Azure ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: SHA of the commit
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${GITHUB_SHA})
          echo "sha=$calculatedSha" >> $GITHUB_OUTPUT


      # - name: Print SHA
      #   run: echo "SHA is ${{ steps.vars.outputs.sha }}"

      - name: Build and push Docker image to ACR
        env:
          ACR_REGISTRY: ${{ vars.ACR_SERVER }}
          IMAGE_NAME: bookvault-api
          IMAGE_TAG: ${{ steps.vars.outputs.sha }}
        run: |
          docker build -f docker/api/Dockerfile -t $ACR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG  -t $ACR_REGISTRY/$IMAGE_NAME:latest .
          docker push $ACR_REGISTRY/$IMAGE_NAME --all-tags





      